### ISSUE TITLE
当List长度为0的时候会报数组下标越界

### ISSUE THREAD

**Issue by Suppermanone** [Othershe/GroupIndexLib#1]
Process: com.test.groupindex, PID: 13505
                                                   java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
                                                       at java.util.ArrayList.get(ArrayList.java:413)
                                                       at com.othershe.groupindexlib.decoration.GroupHeaderItemDecoration.onDrawOver(GroupHeaderItemDecoration.java:89)
                                                       at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3796)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:16171)
                                                       at android.view.View.draw(View.java:16955)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:16166)
                                                       at android.view.View.draw(View.java:16955)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:16166)
                                                       at android.view.View.draw(View.java:16955)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:16166)
                                                       at android.view.View.draw(View.java:16955)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:16166)
                                                       at android.view.View.draw(View.java:16955)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:16166)
                                                       at android.view.View.draw(View.java:16955)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                       at android.view.View.draw(View.java:17192)
                                                       at com.android.internal.policy.DecorView.draw(DecorView.java:756)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:16171)
                                                       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
                                                       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
                                                       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
                                                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
                                                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6236)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
                                                       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by Likeyong** [comment]
我也遇到了这个问题，想问一下是否有办法解决，其次有没有动态关闭  插入头分组的函数

**Comment by Likeyong** [comment]
因为做联系人搜索，但是搜索结果为0，然后报了数组越界

**Comment by shehuan** [comment]
问题已修复
